### ISSUE TITLE
Stateful/Stateless Components

### ISSUE THREAD

**Issue by Natia94** [KillTheMessenger/Interspect#14]
How handle components that has individual state and constantly edited and deleted 
 *due to Monday morning

**Comment by neuhausneuhaus** [comment]
From my research, it seems that the component that brought up this question (the dynamically created RouteItems which move from stage, to the mock server and back) are not a special case at all, but are in fact an example of a typical Redux use case. The RouteItems(or wtvr we want to call them) should be Presentational Components, just like items in a todo list, or products in a shopping cart. 
I think that store should have a list of items, each of which having a property indicating whether they are a currently a part of the stage or mock server.
