### ISSUE TITLE
Gut the components (and probably some containers too)

### ISSUE THREAD

**Issue by neuhausneuhaus** [KillTheMessenger/Interspect#15]
IT'S TIME YOU GUYS. 🔥 We have to cut out the existing component structure, and replace with a new structure of "skeleton" components set up to use Redux.

To be clear, this task does not include adding any functionality to these new components, just clearing out the old ones, setting up a new structure, and hooking up Redux.

Feel free to remove any packages that are now superfluous, though.

**Comment by neuhausneuhaus** [comment]
@wmagee03 
GUT EM

**Comment by Natia94** [comment]
Three Components should be "gut" 👇
1. TestComponents.jsx
2. PerformanceMatrix.jsx
3. DummyData.jsx
