### ISSUE TITLE
MVP Backend

### ISSUE THREAD

**Issue by Natia94** [KillTheMessenger/Interspect#39]
Description coming sooooooon...

![](https://i.giphy.com/media/51Uiuy5QBZNkoF3b2Z/giphy.webp)

**Comment by neuhausneuhaus** [comment]
- [x] Listen for changes to “server” store
   - Turn server on or off
- [x] Listen for changes to body item store
   - If collection is “HOSTED_ITEMS”, make routes for item, that respond according to spec.
-  [x] Listen for changes to Port # Store
   - Change mock server port # accordingly
